version: '3.8'

services:
  metabot:
    build:
      context: .
      dockerfile: metabot.dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - './metabot:/metabot/metabot'
    ports:
      - 8000:8000
    env_file: .env

  checks:
    image: 'metabot_checks'
    build:
      context: .
      dockerfile: checks.dockerfile

  flake8:
    image: 'metabot_checks'
    command: flake8 .
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True

  mypy:
    image: 'metabot_checks'
    command: mypy metabot
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True
