version: '3.8'

services:

  # DATABASES

  redis:
    image: 'redis:6.0.1'
    expose:
      - 6379

  mongo:
    image: 'mongo:4.2.5'
    restart: always
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  # METABOT

  metabot:
    build:
      context: metabot
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - './metabot:/app'
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file: metabot/.env

  # METABOT MODULES

  help:
    build:
      context: modules/help
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
    - './modules/help:/app'
    depends_on:
      - metabot
    env_file: modules/help/.env

  vacations:
    build:
      context: modules/vacations
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - './modules/vacations:/app'
    depends_on:
      - metabot
      - mongo
    env_file: modules/vacations/.env

  feedback:
    build:
      context: modules/feedback
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - './modules/feedback:/app'
    depends_on:
      - metabot
      - mongo
    env_file: modules/feedback/.env

  # LINT & TYPE CHECKING

  lint:
    image: 'metabot_lint'
    build:
      context: .
      dockerfile: lint.dockerfile

  flake8:
    image: 'metabot_lint'
    command: flake8 .
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True

  mypy:
    image: 'metabot_lint'
    command: mypy metabot fastapi-metabot modules/help modules/vacations modules/feedback
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True


volumes:
  mongodb:
