version: '3.8'

services:
  redis:
    image: 'redis:6.0.1'
    expose:
      - 6379

  metabot:
    build:
      context: .
      dockerfile: metabot.dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - './metabot:/app/metabot'
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file: .env

  example:
    build:
      context: modules/example
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
    - './modules/example:/app'
    depends_on:
      - metabot

  lint:
    image: 'metabot_lint'
    build:
      context: .
      dockerfile: lint.dockerfile

  flake8:
    image: 'metabot_lint'
    command: flake8 .
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True

  mypy:
    image: 'metabot_lint'
    command: mypy metabot fastapi-metabot
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: True
