name: Test fastapi_metabot package

on:
  push:
    branches: [ master ]
    paths:
      - "fastapi-metabot/**"
  pull_request:
    branches: [ master ]
    paths:
      - "fastapi-metabot/**"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        cd fastapi-metabot
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
    - name: Test with pytest
      run: |
        cd fastapi-metabot
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest
