name: modules/feedback

on:
  push:
    branches: [ master ]
    paths:
      - "modules/feedback/**"
  pull_request:
    branches: [ master ]
    paths:
      - "modules/feedback/**"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('lint-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lint-requirements.txt
      - name: Lint with flake8
        run: |
          flake8 modules/feedback --count --show-source --statistics
      - name: Type check with mypy
        run: |
          mypy modules/feedback

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        cd modules/feedback
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
    - name: Test with pytest
      run: |
        cd modules/feedback
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest
